config/routes.rb
Rails.application.routes.draw do
  get '/record', to: 'dish_images#new'
  post '/record', to: 'dish_images#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root 'dishes#index'
	
	resources :dishes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dish.rb
class Dish < ApplicationRecord
	has_many :dish_images
	validates :name, presence: true
	validates :url, presence: true
end

app/models/dish_image.rb
class DishImage < ApplicationRecord
	belongs_to :dish
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include DishesHelper
end

app/controllers/dish_images_controller.rb
class DishImagesController < ApplicationController
  # local開発でCan't verify CSRF token authenticityと言われてしまうことへの対策
  # https://qiita.com/nishina555/items/4ffaf5cc57a384b66230
  # セキュリティ的に大丈夫か？
  skip_before_action :verify_authenticity_token

  def create
    dish_id = params[:dish_id]
    image_binary = params[:image]
    if image_binary == nil
      render json: {"message": "400 bad request. Image file might be incollect."}
      return
    end

    filename = generate_random_filename()
    save_image(image_binary, filename)
    @dish_image = DishImage.new(dish_id: dish_id, filename: filename)
    if @dish_image.save
      dish = Dish.find_by_id(dish_id)
      redirect_to dish_url(dish)
    else
      render json: {"message": "500 Internal Server Error"}
    end
  end

  private
    def generate_random_filename()
      return ('a'..'z').to_a.shuffle[0..7].join
    end

    def save_image(image_binary, filename)
      File.binwrite("public/dish_images/#{filename}", image_binary.read)
    end

end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  # local開発でCan't verify CSRF token authenticityと言われてしまうことへの対策
  # https://qiita.com/nishina555/items/4ffaf5cc57a384b66230
  # セキュリティ的に大丈夫か？
  skip_before_action :verify_authenticity_token

  def index
    render json: get_index_dishes()
  end

  def show
    dish_id = params[:id].to_i
    if Dish.ids.include?(dish_id)
      render json: get_show_dish(dish_id)
    else
      render json: {"message": "404 Not Found"}
    end
  end

  def create
    @dish = Dish.new(dish_params)
    if @dish.save
      render json: @dish
    else
      render json: {"message": "500 Internal Server Error"}
    end
  end

  def update
    dish_id = params[:id].to_i
    if Dish.ids.include?(dish_id)
      @dish = Dish.find(dish_id)
      if @dish.update_attributes(dish_params)
        render json: @dish
      else
        render json: {"message": "500 Internal Server Error"}
      end
    else
      render json: {"message": "400 Bad Request. The dish doesn't exist."}
    end
  end

  def destroy
    dish_id = params[:id].to_i
    dish_exist = Dish.ids.include?(dish_id)
    has_no_image = DishImage.where(dish_id: dish_id).empty?
    if dish_exist && has_no_image
      dish = Dish.find(dish_id)
      dish.destroy
      render json: {"message": "204 Resource Deleted Successfully"}
    elsif not dish_exist
      render json: {"message": "400 Bad Request. The dish doesn't exist."}
    elsif not has_no_image  # 画像が登録されている料理を消すと、DishImages側は削除されずに不整合になってしまうので、いったんエラー処理
      render json: {"message": "400 Bad Request. A dish with image cannot be destroyed."}
    end
  end

  private

    # マスアサインメント対策
    def dish_params
      params.require(:dish).permit(:name, :url, :memo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dish_images_helper.rb
module DishImagesHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
	def get_index_dishes
		dishes = []
    Dish.all.reverse_each do |dish|
      dish_id = dish.id
      last_image_filename = DishImage.where(dish_id: dish_id).to_ary()[-1]  # TODO: 料理数と同じ回数のrequestが発生するので遅い
      dish_dict = {id: dish_id, name: dish.name, url: dish.url, memo: dish.memo, image: last_image_filename}
      dishes.append dish_dict
     end
    return dishes
	end

	def get_show_dish(dish_id)
		dish = Dish.find(dish_id)
		dish_images = DishImage.where(dish_id: dish_id).to_ary()
		# TODO: 料理画像も返す(どういう形式で返すのがいい？)
		return dish
	end
end

app/views/dish_images/new.html.erb
<h1>食べたごはんの記録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@dish_image, url: record_path) do |f| %>
      <%= render 'shared/dish_image_error_messages' %>
    
      <%= f.label :dish_id, "料理ID" %>
      <%= f.text_field :dish_id, class: 'form-control'  %>
      
      <%= f.file_field :image, class: 'form-control'  %>

      <%= f.submit "登録", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/dishes/_form.html.erb
<%= form_for(@dish, url: yield(:form_for)) do |f| %>
  <%= render 'shared/dish_error_messages' %>

  <%= f.label :name, "料理名" %>
  <%= f.text_field :name %>

  <%= f.label :url, "URL" %>
  <%= f.url_field :url %>
  
  <%= f.label :memo, "メモ" %>
  <%= f.text_field :memo %>

  <%= f.submit "登録", class: "btn btn-primary" %>
<% end %>

app/views/dishes/edit.html.erb
<% provide(:form_for, dish_path(@dish)) %>
<h1>ごはんの編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/dishes/index.html.erb
<h1>ごはん一覧</h1>
<% @dishes.each do |dish| %>
	<div class="gohan">
		<div class="gohan-image">
			<% if dish[:image] != nil %>
				<a href=<%= dish_path(dish) %>><img src="<%= "/dish_images/#{dish[:image].filename}" %>" width="100"></a>
			<% end %>
		</div>
		<div class="gohan-content">
			<h3><a href=<%= dish_path(dish) %>><%= dish[:name] %></a></h3>
			<p><a href=<%= dish[:url] %>><%= dish[:url] %></a></p>
			<p><%= dish[:memo] %></p>
		</div>
	</div>
<% end %>

app/views/dishes/new.html.erb
<% provide(:form_for, dishes_path) %>
<h1>新しいごはんの追加</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/dishes/show.html.erb
<p><%= @dish.name %></p>

<p><%= @dish.url %></p>

<p><%= @dish.memo %></p>

<h3>料理の画像</h3>
<% @dish_images.each do |dish_image| %>
    <img src="<%= "/dish_images/#{dish_image.filename}" %>" width="100">
<% end %>

<p><%= link_to "編集", edit_dish_path(@dish) %></p>

<p><%= link_to "削除", dish_path(@dish), method: :delete, data: {confirm: "本当に削除しますか？"} %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cook Pod</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "CookPod", root_path, id: "logo" %>
        <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "ごはん一覧",   root_path %></li>
          <li><%= link_to "新しいごはんの追加", new_dish_path %></li>
          <li><%= link_to "食べたごはんの記録", record_path %></li>
        </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_dish_error_messages.html.erb
<% if @dish.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
     <%= @dish.errors.count %>個のエラーが存在します。
    </div>
    <ul>
    <% @dish.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_dish_image_error_messages.html.erb
<% if @dish_image.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
     <%= @dish_image.errors.count %>個のエラーが存在します。
    </div>
    <ul>
    <% @dish_image.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @dish_image.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
     <%= @dish_image.errors.count %>個のエラーが存在します。
    </div>
    <ul>
    <% @dish_image.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>